name: Bruxall
favicon: null
layout_spectrum: 0.02209143782965839
typography_spectrum: 0.697408871492371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6503311041742563
  lightness: 0.6670400893781334
  saturation: 0.9660452990792692
  rhythmicContrast: 0.5240882753860205
purpose: []
